### ISSUE TITLE
License LGPL or GPL

### ISSUE THREAD

**Issue by anara123** [seamustuohy/RTFDE#1]
Hello Seamus

Trying to use your library as part of my work. 
Have to say, Nice Work and thanks for making it open source!

My question is whether the license here is LGPL or GPL.
Because according to the LICENSCE file it is GPL.
According to https://pypi.org/project/RTFDE/ and https://github.com/seamustuohy/RTFDE/blob/main/setup.py#L18 it is LGPL.

**Comment by seamustuohy** [comment]
Oh, it should be LGPL across the board. I'll update that! (Sorry for the delay I must have missed the issue email.)

**Comment by anara123** [comment]
Thanks a lot!

**Comment by seamustuohy** [comment]
Happy to help. Please do let me know if you find any bugs or had to add any new processing steps for it to serve your needs. It was built because no other Python library solved this problem and I needed it to support a previous project I contributed to a while ago. But, since I rarely use this code I'm a bit ignorant to any edge cases it might hit up against.

**Comment by anara123** [comment]
I know, I was looking for a library like this, but I didn't find one that solved the problem properly.
If we will find any bugs, we will let you know or even open a pull request to fix.
